### ISSUE TITLE
Tips on how to run async code

### ISSUE THREAD

**Issue by simonw** [bpcreech/PyMiniRacer#7]
### Steps to reproduce

```pycon
>>> import py_mini_racer
>>> context = py_mini_racer.MiniRacer()
>>> result = context.eval("""
... async function pretendToDelay() {
...     return new Promise(resolve => {
...         setTimeout(() => resolve('Data loaded!'), 1000);
...     });
... }
... pretendToDelay();
... """)
>>> print(result, result.__dict__)
<py_mini_racer.py_mini_racer.JSObject object at 0x100ec6620> {'id': 965435}
```

That code to paste:

```python
import py_mini_racer
context = py_mini_racer.MiniRacer()
result = context.eval("""
async function pretendToDelay() {
    return new Promise(resolve => {
        setTimeout(() => resolve('Data loaded!'), 1000);
    });
}
pretendToDelay();
""")
print(result, result.__dict__)
```
I tried using `await pretendToDelay();` on the last line instead and got this:

`py_mini_racer.py_mini_racer.JSParseException: SyntaxError: await is only valid in async functions and the top level bodies of modules`

### Expected behavior

I'm trying to figure out how to return the result from resolving that promise.

Assuming there's a pattern for doing this, it would be great if the test suite and documentation described it!

**Comment by bpcreech** [comment]
There isn't a pattern for this except for polling. [`test_async` in `tests/test_eval.py`](https://github.com/bpcreech/PyMiniRacer/blob/5161d99a39076c36209519c9601d32546c8d276b/tests/test_eval.py#L215C5-L215C15) does this.

Also, you didn't run into this yet, but `setTimeout` doesn't exist, because [it's an HTML DOM and Web Worker API](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) not an ECMAScript API. That test above uses `Atomics.waitAsync` as a workaround for that.

[I'm working on](https://github.com/bpcreech/PyMiniRacer/tree/async4) adding proper async support, modeled as async/await on the Python side too. This requires changing the Python<->DLL interaction to use callbacks. I have this working on a branch (or, well, 5 branches with iterations of this)... current status is it adds 40x overhead to all calls, so I'm working on that before landing it. :)

**Comment by simonw** [comment]
Neat! That `test_async` polling example is exactly what I needed. Sounds like it's not worth documenting right now though if a better solution is incoming soon.

Generally I'd find documentation on "JavaScript patterns that work well with PyMiniRacer" to be super useful.

**Comment by bpcreech** [comment]
Sounds good, feel free to start a "js_cookbook.md" if you want! For the immediate future I'm focusing instead on making async work, and before that, making the pre-commit GH Action actually work. :)

**Comment by bpcreech** [comment]
An update: https://github.com/bpcreech/PyMiniRacer/pull/14 will resolve this in `v0.10.0`. But I plan to release a `v0.9.0` first with some foundational work, as a separate release to help bisect issues in case anything goes wrong with all the C++ refactoring I'm doing in here. So this should be resolved in a few days (PyMiniRacer builds are super slow, what with emulated aarch64 on the free GH runners!).

**Comment by bpcreech** [comment]
Ok v0.10.0, just pushed to PyPI, should resolve, by adding and documenting support for JS Promises, awaitable via blocking and asyncio APIs.

I documented this in the README... I didn't go to the length of starting a "cookbook" yet because the README is still of manageable length, I think.
